---
- name: install
  yum:
    name: "{{ asterisk_pkg_names }}"
    enablerepo: "{{ asterisk_enablerepo | default(omit, True) }}"

- name: systemd service definition
  copy:
    src: asterisk.service
    dest: /usr/lib/systemd/system/asterisk.service
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: systemd_unit_file_t
  notify:
    - systemd daemon-reload

- name: config
  copy:
    src: "{{ item }}"
    dest: "/etc/asterisk/{{ item }}"
    owner: asterisk
    group: asterisk
    mode: 0640
  with_items: "{{ asterisk_configs | default([]) | list }}"
  notify:
    - asterisk service reload

- name: service enabled
  service:
    name: asterisk
    enabled: true
  tags:
    - services

- name: "service state={{ asterisk_svc_state }}"
  service:
    name: asterisk
    state: "{{ asterisk_svc_state }}"
  tags:
    - services
