---
- name: import repo
  get_url:
    url: "{{ asterisk_yum_repo_url }}"
    dest: /etc/yum.repos.d/asterisk.repo
    mode: 0640
  become: yes

- name: import gpg key
  rpm_key:
    key: "{{ asterisk_yum_gpg_url }}"
    state: present
  become: yes

- name: install
  yum:
    name:
      - asterisk
      - asterisk-voicemail
      - asterisk-pjsip
    enablerepo: "{{ asterisk_enablerepo | default(omit, True) }}"
  become: yes

- name: config
  copy:
    src: "{{ item }}"
    dest: "/etc/asterisk/{{ item }}"
    owner: asterisk
    group: asterisk
    mode: 0640
  with_items: "{{ asterisk_configs | default([]) | list }}"
  notify:
    - systemd asterisk restart
  become: yes

- name: systemd asterisk start enable
  systemd:
    name: asterisk
    state: started
    enabled: yes
  when: ansible_distribution_major_version|int > 6
  tags:
    - asterisk
    - services
  become: yes
